### ISSUE TITLE
UFX.Orleans.SignalRBackplane in Production

### ISSUE THREAD

**Issue by Ceyword** [unifiedfx/UFX.Orleans.SignalRBackplane#14]
Hello,
Thank you for a very useful library.
My question, can we use UFX.Orleans.SignalRBackplane  in production? 
Thank you

**Comment by stephenwelsh** [comment]
Hi,
We (UnifiedFX) have not used it in production yet, however the @michaelmcneilnet does/has used it in at least one production project that we are aware of.

This is not a primary component for us yet so assistance to issues may be limited until we deploy to our production environment a few months from now.

**Comment by Ceyword** [comment]
Thank you @stephenwelsh for your prompt response. 

@michaelmcneilnet can you kindly share your experience with production usage? Pros, cons and challenges maybe? Thank you in advance.

**Comment by stephenwelsh** [comment]
@michaelmcneilnet was mistakenly removed from this repo a few weeks back, I've added him back in so he should be notified now.
I've decided to deploy this library to our product this weekend and initial testing looks good, however not expecting production level activity for a number of months. If we find any issues during load testing we shall either fix them or update the status of this library accordingly, I'll close this issue for now.

**Comment by hendrikdevloed** [comment]
Now that some months have passed, I would be quite interested in having an update on pitfalls or good experiences of running this in production... However brief it may be.

Thanks!

**Comment by stephenwelsh** [comment]
> Now that some months have passed, I would be quite interested in having an update on pitfalls or good experiences of running this in production... However brief it may be.

From our side (UnifiedFX) not too much to report, not stressed to any level but has been as stable as the built-in backplane so-far. Our environment is currently only scaled to a single instance of SignalR Hub however as all messaging goes through the Orleans backplane its still validates the backplane operation.

**Comment by Ceyword** [comment]
> Now that some months have passed, I would be quite interested in having an update on pitfalls or good experiences of running this in production... However brief it may be.
> 
> Thanks!

We had to abruptly re-focus our attention to an upstream service, away from the signalr-dependent one. We have been at it since. Anyway, our initial tests with UFX.Orleans.SignalRBackplane was good and we are appreciative of the library. We will provide updates on any pertinent observations as they occur.
