### ISSUE TITLE
UFX.Orleans.SignalRBackplane Detailed Configuration Reference

### ISSUE THREAD

**Issue by Ceyword** [unifiedfx/UFX.Orleans.SignalRBackplane#15]
Hello @stephenwelsh ,
The provided example point to  configuring GrainStorage, Reminder and AddSignalRBackplane :
```
builder.Host
    .UseOrleans(siloBuilder => siloBuilder
        .AddMemoryGrainStorage(UFX.Orleans.SignalRBackplane.Constants.StorageName)
        .UseInMemoryReminderService()
        .AddSignalRBackplane()
    ); 
```
1- Can you help with a detailed configuration example that we can use as reference?
2- Particularly, do we need to configure Clustering and import required dependencies or is it already implemented under the hood?
3- Can I take it that this library does not use Streaming?

Thank you.

**Comment by stephenwelsh** [comment]
Hi @Ceyword,

1. Might take a few days but I'll aim to provide additional detail on a production level example
2. You still need to configure the Orleans cluster as usual, this effectively sits on top of a working Orleans cluster
3. Correct, the main [SignalR.Orleans](https://github.com/OrleansContrib/SignalR.Orleans) library uses streaming which is the main reason we put this library together as our requirements are for immediate (non-polling) SignalR events so instead use [**IGrainObserver**](https://learn.microsoft.com/en-us/dotnet/orleans/grains/observers)

**Comment by Ceyword** [comment]
Hello @stephenwelsh  , 
thank you for your response.
1- Yes few days is fine, I look forward to it.
2- Understood.
3- SignalR uses long polling, websockets and server-side events as necessary. When you say _(non-polling) SignalR_, do you mean that SignalR long polling, as a connection option, will not be supported? If so will websockets be supported?

**Comment by stephenwelsh** [comment]
Hi @Ceyword,
> 3- SignalR uses long polling, websockets and server-side events as necessary. When you say _(non-polling) SignalR_, do you mean that SignalR long polling, as a connection option, will not be supported? If so will websockets be supported?

I'm referring to the Orleans Streams [Pulling Agent](https://learn.microsoft.com/en-us/dotnet/orleans/implementation/streams-implementation/#pulling-agents). Nothing to do with SignalR, this library has no dependency on SignalR connection methods, obviously WebSockets for SignalR is best though 😉
This library avoids using Orleans Streams Pulling Agent and uses [IGrainObserver](https://learn.microsoft.com/en-us/dotnet/orleans/grains/observers) allowing for SignalR backplane (server to server) communication to be immediate.
So in principle if your SignalR connection is WebSockets and using this library it should provide the lowest latency for a multi-server SignalR Hub.

**Comment by Ceyword** [comment]
Thank you for the answers

**Comment by stephenwelsh** [comment]
Hi @Ceyword,
I've updated the Readme with a complete setup example for MongoDB:

```cs
using Orleans.Providers.MongoDB.Configuration;
using UFX.Orleans.SignalRBackplane;

builder.Host
    .UseOrleans(siloBuilder => siloBuilder
        .UseMongoDBClient("MongoDBConnectionString")
        .AddMongoDBGrainStorageAsDefault(options =>
        {
            options.Configure(storage =>
            {
                storage.DatabaseName = "DefaultStorage";
            });
        })
        .AddMongoDBGrainStorage(Constants.StorageName, options =>
        {
            options.Configure(storage =>
            {
                storage.DatabaseName = "SignalRBackPlaneGrainStoreage";
            });
        })
        .UseMongoDBReminders(options =>
        {
            options.DatabaseName = "SignalRBackPlaneRemindersStoreage";
        })
        .Configure<Orleans.Configuration.ClusterOptions>(options =>
        {
            options.ClusterId = "OrleansClusterId";
            options.ServiceId = "OrleansServiceId";
        })
        .AddSignalRBackplane();
    );
```
